Fix exception with zero value in StackBar (#565)
Fix following exception.

```ruby
require 'gruff'

g = Gruff::StackedBar.new
g.data :A, [0, 5, 4]
g.data :B, [0, 3, 8]
g.show_labels_for_bar_values = true
g.write("gruff.png")
```

```
/home/watson/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/gruff-0.15.0/lib/gruff/helper/bar_value_label.rb:64:in `block in prepare_rendering': undefined method `sum' for nil:NilClass (NoMethodError)

        value = bars.sum(&:value)
                    ^^^^
        from /home/watson/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/gruff-0.15.0/lib/gruff/helper/bar_value_label.rb:63:in `each'
        from /home/watson/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/gruff-0.15.0/lib/gruff/helper/bar_value_label.rb:63:in `prepare_rendering'
        from /home/watson/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/gruff-0.15.0/lib/gruff/stacked_bar.rb:88:in `draw_graph'
        from /home/watson/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/gruff-0.15.0/lib/gruff/base.rb:505:in `draw'
        from /home/watson/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/gruff-0.15.0/lib/gruff/base.rb:471:in `to_image'
        from /home/watson/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/gruff-0.15.0/lib/gruff/base.rb:453:in `write'
        from gruff2.rb:7:in `<main>'
```